name: cyber-assessment-env
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.10
  
  # Web Framework
  - flask>=2.0.0
  
  # Data Processing
  - pandas>=1.3.0
  - numpy>=1.21.0
  - openpyxl>=3.0.0
  
  # HTTP Requests
  - requests>=2.25.0
  
  # Document Processing
  - python-docx>=0.8.11
  - pypdf2>=2.0.0
  - python-pptx>=0.6.21
  
  # Machine Learning & AI
  - transformers>=4.20.0
  - torch>=1.12.0
  - scikit-learn>=1.0.0
  
  # Data Visualization (optional)
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  
  # Development Tools
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  
  # Pip dependencies (not available in conda)
  - pip
  - pip:
    - ollama>=0.1.0
    # Add other pip-only packages here as needed

# Optional: specify prefix for environment location
# prefix: /path/to/envs/cyber-assessment-env
