name: cyber-assessment-env-minimal
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python only
  - python=3.10
  
  # Essential packages only
  - flask>=2.0.0
  - pandas>=1.3.0
  - numpy>=1.21.0
  - requests>=2.25.0
  
  # Pip dependencies
  - pip
  - pip:
    - ollama>=0.1.0
